# Documentation: https://github.com/bcgov/von-agent-template/tree/master/von-x-agent/config

forms:
  ian-comy-registration:
    path: /ian-co/my-registration
    type: issue-credential
    schema_name: my-registration.ian-co
    page_title: Title for my-registration.ian-co
    title: Title for my-registration.ian-co
    template: bcgov.index.html
    description: The my-registration credential issued by ian-co
    explanation: Use the form below to issue a Credential.
    fields:
    - name: registration_date
      label: registration_date
      type: date
      required: false
    - name: entity_name
      label: entity_name
      type: text
      required: true
    - name: entity_name_effective
      label: entity_name_effective
      type: date
      required: true
    - name: entity_address
      label: Mailing Address
      type: address
      required: true
    - name: entity_status
      label: entity_status
      type: select
      options:
      - todo-1
      - todo-2
      - todo-3
      required: true
    - name: entity_status_effective
      label: entity_status_effective
      type: date
      required: true
    - name: entity_type
      label: entity_type
      type: text
      required: true
    - name: registered_jurisdiction
      label: registered_jurisdiction
      type: text
      required: false
    - name: effective_date
      label: effective_date
      type: date
      required: true
    - name: expiry_date
      label: expiry_date
      type: date
      required: false
    mapping:
      attributes:
      - name: corp_num
        from: helper
        source: uuid
  ian-comy-relationship:
    path: /ian-co/my-relationship
    type: issue-credential
    schema_name: my-relationship.ian-co
    page_title: Title for my-relationship.ian-co
    title: Title for my-relationship.ian-co
    template: bcgov.index.html
    description: The relationship between two organizations
    explanation: Use the form below to issue a Credential.
    proof_request:
      id: greenlight_registration
      connection_id: bctob
    fields:
    - name: corp_num
      label: corp_num
      type: text
      required: true
    - name: associated_corp_num
      label: associated_corp_num
      type: text
      required: true
    - name: associated_registration_name
      label: associated_registration_name
      type: text
      required: false
    - name: relationship
      label: relationship
      type: text
      required: true
    - name: relationship_description
      label: relationship_description
      type: text
      required: true
    - name: relationship_status
      label: relationship_status
      type: select
      options:
      - todo-1
      - todo-2
      - todo-3
      required: true
    - name: relationship_status_effective
      label: relationship_status_effective
      type: date
      required: false
    - name: effective_date
      label: effective_date
      type: date
      required: true
    - name: expiry_date
      label: expiry_date
      type: date
      required: false
    mapping:
      attributes: []
  ian-coian-permit:
    path: /ian-co/ian-permit
    type: issue-credential
    schema_name: ian-permit.ian-co
    page_title: Title for ian-permit.ian-co
    title: Title for ian-permit.ian-co
    template: bcgov.index.html
    description: The ian-permit credential issued by ian-co
    explanation: Use the form below to issue a Credential.
    proof_request:
      id: greenlight_registration
      connection_id: bctob
    fields:
    - name: corp_num
      label: corp_num
      type: text
      required: true
    - name: entity_name
      label: entity_name
      type: text
      required: true
    - name: permit_type
      label: permit_type
      type: select
      options:
      - todo-1
      - todo-2
      - todo-3
      required: true
    - name: permit_issued_date
      label: permit_issued_date
      type: date
      required: true
    - name: permit_status
      label: permit_status
      type: select
      options:
      - todo-1
      - todo-2
      - todo-3
      required: true
    - name: effective_date
      label: effective_date
      type: date
      required: true
    mapping:
      attributes:
      - name: permit_id
        from: helper
        source: uuid

### eof ###
