# Documentation: https://github.com/bcgov/von-agent-template/tree/master/von-x-agent/config

forms:
  pspc-tender-credential:

    # URL for the Web form - becomes <server>/<path> e.g. http://localhost:5000/gc/gc-tender-cred
    path: /gc/gc-tender-credential
  
    # type is always "issue-credential"
    type: issue-credential
  
    schema_name: gc-tender-credential.gc
    page_title: GC Tender
    title: Application for gc-tender-credential
  
    # Templates are defined in von-x-agent/templates
    template: bcgov.index.html
  
    description: >
      GC issues gc-tender-credential credentials to organizations to authorize those organizations to be able to do something.
  
    explanation: Use the form below to apply for a pspc-tender-credential for your organization.

    proof_request:
      id: registration
      connection_id: bctob

    #js_includes:
    #  - src: js/file.js

    # "fields" are displayed on the UI for the user to enter values
    fields:
      - name: subject_id
        label: Subject ID
        type: text
        required: true

      - name: credential_id
        label: Credential ID
        type: text
        required: true

      - name: solicitation_number
        label: Solicitation Number
        type: text
        required: true

      - name: title_fr
        label: Title French
        type: text
        required: true
      
      - name: title_en
        label: Title English
        type: text
        required: true
      
      - name: publication_date
        label: Publication Date
        type: date
        required: true
      
      - name: amendment_number
        label: Amendment Number
        type: text
        required: true
      
      - name: amendment_date
        label: Amendment Date
        type: date
        required: true

      - name: closing_date
        label: Closing Date
        type: date
        required: true

      - name: status
        label: Status
        type: text
        required: true

      - name: gsin_number
        label: GSIN Number
        type: text
        required: true

      - name: gsin_en
        label: GSIN English
        type: text
        required: true

      - name: gsin_fr
        label: GSIN French
        type: text
        required: true

      - name: tender_uri_fr
        label: Tender URI French
        type: text
        required: true

      - name: tender_uri_en
        label: Tender URI English
        type: text
        required: true
      
    
    

### eof ###
