# Documentation: https://github.com/bcgov/von-agent-template/tree/master/von-x-agent/config

issuers:
  myorg:
    name: Ian Company
    abbreviation: ian-co
    url: https://www.ian-co.ca/ian-co-info-page
    email: info@ian-co.ca
    logo_path: ../assets/img/ian-co-logo.jpg
    endpoint: $ENDPOINT_URL

    connection:
      type: TheOrgBook
      api_url: $TOB_API_URL
      sign_target: false

    credential_types:
    - description: The my-registration credential issued by ian-co
      schema: my-registration.ian-co
      issuer_url: $ENDPOINT_URL/ian-co/my-registration
      credential:
        effective_date:
          input: effective_date
          from: claim
        revoked_date:
          input: expiry_date
          from: claim
      topic:
        source_id:
          input: corp_num
          from: claim
        type:
          input: my-registration.ian-co
          from: value
      mapping:
      - model: attribute
        fields:
          type:
            input: corp_num
            from: value
          value:
            input: corp_num
            from: claim
      - model: attribute
        fields:
          type:
            input: registration_date
            from: value
          format:
            input: datetime
            from: value
          value:
            input: registration_date
            from: claim
      - model: name
        fields:
          text:
            input: entity_name
            from: claim
          type:
            input: entity_name
            from: value
      - model: attribute
        fields:
          type:
            input: entity_name_effective
            from: value
          format:
            input: datetime
            from: value
          value:
            input: entity_name_effective
            from: claim
      - model: address
        fields:
          addressee:
            input: addressee
            from: claim
          civic_address:
            input: address_line_1
            from: claim
          city:
            input: city
            from: claim
          province:
            input: province
            from: claim
          postal_code:
            input: postal_code
            from: claim
          country:
            input: country
            from: claim
      - model: attribute
        fields:
          type:
            input: entity_status
            from: value
          value:
            input: entity_status
            from: claim
      - model: attribute
        fields:
          type:
            input: entity_status_effective
            from: value
          format:
            input: datetime
            from: value
          value:
            input: entity_status_effective
            from: claim
      - model: attribute
        fields:
          type:
            input: entity_type
            from: value
          value:
            input: entity_type
            from: claim
      - model: attribute
        fields:
          type:
            input: registered_jurisdiction
            from: value
          value:
            input: registered_jurisdiction
            from: claim
      - model: attribute
        fields:
          type:
            input: effective_date
            from: value
          format:
            input: datetime
            from: value
          value:
            input: effective_date
            from: claim
      - model: attribute
        fields:
          type:
            input: expiry_date
            from: value
          format:
            input: datetime
            from: value
          value:
            input: expiry_date
            from: claim
    - description: The relationship between two organizations
      schema: my-relationship.ian-co
      issuer_url: $ENDPOINT_URL/ian-co/my-relationship
      depends_on:
      - greenlight_registration
      credential:
        effective_date:
          input: effective_date
          from: claim
      topic:
        related_source_id:
          input: associated_corp_num
          from: claim
        related_type:
          input: my-registration.ian-co
          from: value
        source_id:
          input: corp_num
          from: claim
        type:
          input: my-registration.ian-co
          from: value
      cardinality_fields:
        - associated_corp_num
      mapping:
      - model: attribute
        fields:
          type:
            input: corp_num
            from: value
          value:
            input: corp_num
            from: claim
      - model: attribute
        fields:
          type:
            input: associated_corp_num
            from: value
          value:
            input: associated_corp_num
            from: claim
      - model: attribute
        fields:
          type:
            input: associated_registration_name
            from: value
          value:
            input: associated_registration_name
            from: claim
      - model: attribute
        fields:
          type:
            input: relationship
            from: value
          value:
            input: relationship
            from: claim
      - model: attribute
        fields:
          type:
            input: relationship_description
            from: value
          value:
            input: relationship_description
            from: claim
      - model: attribute
        fields:
          type:
            input: relationship_status
            from: value
          value:
            input: relationship_status
            from: claim
      - model: attribute
        fields:
          type:
            input: relationship_status_effective
            from: value
          format:
            input: datetime
            from: value
          value:
            input: relationship_status_effective
            from: claim
      - model: attribute
        fields:
          type:
            input: effective_date
            from: value
          format:
            input: datetime
            from: value
          value:
            input: effective_date
            from: claim
      - model: attribute
        fields:
          type:
            input: expiry_date
            from: value
          format:
            input: datetime
            from: value
          value:
            input: expiry_date
            from: claim
    - description: The ian-permit credential issued by ian-co
      schema: ian-permit.ian-co
      issuer_url: $ENDPOINT_URL/ian-co/ian-permit
      depends_on:
      - greenlight_registration
      credential:
        effective_date:
          input: effective_date
          from: claim
      topic:
        source_id:
          input: corp_num
          from: claim
        type:
          input: my-registration.ian-co
          from: value
      mapping:
      - model: attribute
        fields:
          type:
            input: corp_num
            from: value
          value:
            input: corp_num
            from: claim
      - model: name
        fields:
          text:
            input: entity_name
            from: claim
          type:
            input: entity_name
            from: value
      - model: attribute
        fields:
          type:
            input: permit_id
            from: value
          value:
            input: permit_id
            from: claim
      - model: attribute
        fields:
          type:
            input: permit_type
            from: value
          value:
            input: permit_type
            from: claim
      - model: attribute
        fields:
          type:
            input: permit_issued_date
            from: value
          format:
            input: datetime
            from: value
          value:
            input: permit_issued_date
            from: claim
      - model: attribute
        fields:
          type:
            input: permit_status
            from: value
          value:
            input: permit_status
            from: claim
      - model: attribute
        fields:
          type:
            input: effective_date
            from: value
          format:
            input: datetime
            from: value
          value:
            input: effective_date
            from: claim

    - description: Cannabis Retail Store Licence
      schema: cannabis-retail-store-licence.lcrb
      label_en: Cannabis Retail Store Licence
      issuer_url: $APPLICATION_URL/cannabis-retail-store-licence
      depends_on:
        - bcreg_registration
      credential:
        effective_date:
          input: effective_date
          from: claim

      # topic identifies the id of the subject of the credential from the foundational credential
      # in BC Gov deployment type is always "registration" as it is from BC Registries
      topic:
        label_en: Registration
        source_id:
          input: registration_id
          from: claim
        type:
          input: registration.registries.ca
          from: value
      cardinality_fields:
        - licence_number
      mapping:
        - model: attribute
          fields:
            type:
              input: issue_date
              from: value
            format:
              input: datetime
              from: value
            value:
              input: issue_date
              from: claim
        - model: attribute
          fields:
            type:
              input: licence_number
              from: value
            value:
              input: licence_number
              from: claim
        - model: attribute
          fields:
            type:
              input: expiry_date
              from: value
            format:
              input: datetime
              from: value
            value:
              input: expiry_date
              from: claim
        - model: attribute
          fields:
            type:
              input: establishment_name
              from: value
            value:
              input: establishment_name
              from: claim
        - model: attribute
          fields:
            type:
              input: effective_date
              from: value
            format:
              input: datetime
              from: value
            value:
              input: effective_date
              from: claim
        - model: address
          fields:
            civic_address:
              input: civic_address
              from: claim
            city:
              input: city
              from: claim
            province:
              input: province
              from: claim
            postal_code:
              input: postal_code
              from: claim
            country:
              input: country
              from: claim

verifiers:
  bctob:
    name: BC OrgBook
    alias: vcr-agent
    connection:
      type: TheOrgBook
      api_url: $TOB_API_URL
      agent_admin_url: $TOB_AGENT_ADMIN_URL

proof_requests:
  greenlight_registration:
    version: '1.0.0'
    schemas:
      - key:
          did: 6qnvgJtqwK44D8LFYnV5Yf
          name: Registered Corporation
          version: '1.0.3'
        attributes:
          - corp_num
          - legal_name


### eof ###
