# Documentation: https://github.com/bcgov/von-agent-template/tree/master/von-x-agent/config

issuers:
  pspc:
    name: Public Services and Procurement Canada 
    abbreviation: PSPC
    url: https://www.canada.ca/home.html
    email: info@canada.ca
    logo_path: ../assets/img/bcreg-logo-square.jpg
    endpoint: $ENDPOINT_URL

    connection:
      type: TheOrgBook
      api_url: $TOB_API_URL
      sign_target: false

    wallet:
      name: ${POSTGRESQL_WALLET_NAME:-myorg_issuer}
      seed: $WALLET_SEED_PSPC
      type: $WALLET_TYPE
      params:
        storage_config:
          url: "$POSTGRESQL_WALLET_HOST:$POSTGRESQL_WALLET_PORT"
      access_creds:
        key: $WALLET_ENCRYPTION_KEY
        storage_credentials:
          account: $POSTGRESQL_WALLET_USER
          password: $POSTGRESQL_WALLET_PASSWORD
          admin_account: ${POSTGRESQL_WALLET_ADMIN_USER:-postgres}
          admin_password: $POSTGRESQL_WALLET_ADMIN_PASSWORD
        key_derivation_method: ARGON2I_MOD

    credential_types:
    - description: PSPC Supplier
      schema: pspc-supplier-credential.pspc
      issuer_url: $APPLICATION_URL/pspc/pspc-supplier-credential

      credential:
        effective_date:
          input: effective_date
          from: claim
      # topic identifies the id of the subject of the credential from the foundational credential
      topic:
        source_id:
          input: subject_id
          from: claim
        type:
          input: pspc-supplier-credential.pspc
          from: value

      mapping:
        # "attribute" defines a generic field in the TOB model
        # "value" identifies where to derive the data value (typically it comes from the claim)
        # "type" - if "value" - is the name of the attribute
        # "format" is an optional data format (default text)
        - model: attribute
          fields:
            type:
              input: credential_id
              from: value
            value:
              input: credential_id
              from: claim
        - model: name
          fields:
            text:
              input: supplier_legal_name
              from: claim
            type:
              input: supplier_legal_name
              from: value
        - model: name
          fields:
            text:
              input: supplier_names
              from: claim
            type:
              input: supplier_names
              from: value
        - model: attribute
          fields:
            type:
              input: supplier_locations
              from: value
            value:
              input: supplier_locations
              from: claim

    - description: PSPC Tender Notice
      schema: pspc-tender-credential.pspc
      issuer_url: $APPLICATION_URL/pspc/pspc-tender-credential

      credential:
        effective_date:
          input: effective_date
          from: claim
      # topic identifies the id of the subject of the credential from the foundational credential
      topic:
        source_id:
          input: subject_id
          from: claim
        type:
          input: pspc-tender-credential.pspc
          from: value

      mapping:
        # "attribute" defines a generic field in the TOB model
        # "value" identifies where to derive the data value (typically it comes from the claim)
        # "type" - if "value" - is the name of the attribute
        # "format" is an optional data format (default text)
        - model: attribute
          fields:
            type:
              input: credential_id
              from: value
            value:
              input: credential_id
              from: claim
        - model: name
          fields:
            text:
              input: solicitation_number
              from: claim
            type:
              input: solicitation_number
              from: value
        - model: name
          fields:
            text:
              input: title_fr
              from: claim
            type:
              input: title_fr
              from: value
        - model: name
          fields:
            text:
              input: title_en
              from: claim
            type:
              input: title_en
              from: value
        - model: attribute
          fields:
            type:
              input: publication_date
              from: value
            value:
              input: publication_date
              from: claim
        - model: attribute
          fields:
            type:
              input: amendment_number
              from: value
            value:
              input: amendment_number
              from: claim
        - model: attribute
          fields:
            type:
              input: amendment_date
              from: value
            value:
              input: amendment_date
              from: claim
        - model: attribute
          fields:
            type:
              input: closing_date
              from: value
            value:
              input: closing_date
              from: claim
        - model: attribute
          fields:
            type:
              input: status
              from: value
            value:
              input: status
              from: claim
        - model: attribute
          fields:
            type:
              input: gsin_number
              from: value
            value:
              input: gsin_number
              from: claim
        - model: attribute
          fields:
            type:
              input: gsin_en
              from: value
            value:
              input: gsin_en
              from: claim
        - model: attribute
          fields:
            type:
              input: gsin_fr
              from: value
            value:
              input: gsin_fr
              from: claim
        - model: attribute
          fields:
            type:
              input: tender_uri_fr
              from: value
            value:
              input: tender_uri_fr
              from: claim
        - model: attribute
          fields:
            type:
              input: tender_uri_en
              from: value
            value:
              input: tender_uri_en
              from: claim

    - description: PSPC Contract
      schema: pspc-contract-credential.pspc
      issuer_url: $APPLICATION_URL/pspc/pspc-contract-credential

      credential:
        effective_date:
          input: effective_date
          from: claim
      # topic identifies the id of the subject of the credential from the foundational credential
      topic:
        source_id:
          input: subject_id
          from: claim
        type:
          input: pspc-contract-credential.pspc
          from: value

      mapping:
        # "attribute" defines a generic field in the TOB model
        # "value" identifies where to derive the data value (typically it comes from the claim)
        # "type" - if "value" - is the name of the attribute
        # "format" is an optional data format (default text)
        - model: attribute
          fields:
            type:
              input: credential_id
              from: value
            value:
              input: credential_id
              from: claim
        - model: name
          fields:
            text:
              input: contract_number
              from: claim
            type:
              input: contract_number
              from: value
        - model: attribute
          fields:
            type:
              input: contract_award_date
              from: value
            value:
              input: contract_award_date
              from: claim
        - model: attribute
          fields:
            type:
              input: amendment_number
              from: value
            value:
              input: amendment_number
              from: claim
        - model: attribute
          fields:
            type:
              input: amendment_date
              from: value
            value:
              input: amendment_date
              from: claim
        - model: attribute
          fields:
            type:
              input: contract_value
              from: value
            value:
              input: contract_value
              from: claim
        - model: attribute
          fields:
            type:
              input: supplier_id
              from: value
            value:
              input: supplier_id
              from: claim
        - model: attribute
          fields:
            type:
              input: supplier_legal_name
              from: value
            value:
              input: supplier_legal_name
              from: claim
        - model: attribute
          fields:
            type:
              input: customer_name_en
              from: value
            value:
              input: customer_name_en
              from: claim
        - model: attribute
          fields:
            type:
              input: customer_name_fr
              from: value
            value:
              input: customer_name_fr
              from: claim
        - model: attribute
          fields:
            type:
              input: customer_address_city
              from: value
            value:
              input: customer_address_city
              from: claim
        - model: attribute
          fields:
            type:
              input: customer_address_prov
              from: value
            value:
              input: customer_address_prov
              from: claim
        - model: attribute
          fields:
            type:
              input: contract_uri_fr
              from: value
            value:
              input: contract_uri_fr
              from: claim
        - model: attribute
          fields:
            type:
              input: contract_uri_en
              from: value
            value:
              input: contract_uri_en
              from: claim
        - model: attribute
          fields:
            type:
              input: contract_title_name_en
              from: value
            value:
              input: contract_title_name_en
              from: claim
        - model: attribute
          fields:
            type:
              input: contract_title_name_fr
              from: value
            value:
              input: contract_title_name_fr
              from: claim

    - description: PSPC Aboriginal Business
      schema: pspc-aboriginal-business-credential.pspc
      issuer_url: $APPLICATION_URL/pspc/pspc-aboriginal-business-credential

      credential:
        effective_date:
          input: effective_date
          from: claim
      # topic identifies the id of the subject of the credential from the foundational credential
      topic:
        source_id:
          input: subject_id
          from: claim
        type:
          input: pspc-aboriginal-business-credential.pspc
          from: value

      mapping:
        # "attribute" defines a generic field in the TOB model
        # "value" identifies where to derive the data value (typically it comes from the claim)
        # "type" - if "value" - is the name of the attribute
        # "format" is an optional data format (default text)
        - model: attribute
          fields:
            type:
              input: credential_id
              from: value
            value:
              input: credential_id
              from: claim
        - model: name
          fields:
            text:
              input: primary_industry
              from: claim
            type:
              input: primary_industry
              from: value
        - model: attribute
          fields:
            type:
              input: supplier_id
              from: value
            value:
              input: supplier_id
              from: claim
        - model: attribute
          fields:
            type:
              input: contact
              from: value
            value:
              input: contact
              from: claim
        - model: attribute
          fields:
            type:
              input: email
              from: value
            value:
              input: email
              from: claim
        - model: attribute
          fields:
            type:
              input: years_active
              from: value
            value:
              input: years_active
              from: claim        

    - description: PSPC Organizational Security
      schema: pspc-organization-security-credential.pspc
      issuer_url: $APPLICATION_URL/pspc/pspc-organization-security-credential

      credential:
        effective_date:
          input: effective_date
          from: claim
      # topic identifies the id of the subject of the credential from the foundational credential
      topic:
        source_id:
          input: subject_id
          from: claim
        type:
          input: pspc-organization-security-credential.pspc
          from: value

      mapping:
        # "attribute" defines a generic field in the TOB model
        # "value" identifies where to derive the data value (typically it comes from the claim)
        # "type" - if "value" - is the name of the attribute
        # "format" is an optional data format (default text)
        - model: attribute
          fields:
            type:
              input: credential_id
              from: value
            value:
              input: credential_id
              from: claim
        - model: name
          fields:
            text:
              input: screening_level
              from: claim
            type:
              input: screening_level
              from: value
        - model: attribute
          fields:
            type:
              input: supplier_id
              from: value
            value:
              input: supplier_id
              from: claim
        - model: attribute
          fields:
            type:
              input: screening_expiry
              from: value
            value:
              input: screening_expiry
              from: claim
        - model: attribute
          fields:
            type:
              input: clearance_level
              from: value
            value:
              input: clearance_level
              from: claim
        - model: attribute
          fields:
            type:
              input: clearance_expiry
              from: value
            value:
              input: clearance_expiry
              from: claim
        - model: attribute
          fields:
            type:
              input: capability_level
              from: value
            value:
              input: capability_level
              from: claim
        - model: attribute
          fields:
            type:
              input: capability_expiry
              from: value
            value:
              input: capability_expiry
              from: claim                                         

    - description: The relationship between Suppliers and Contracts
      schema: pspc-supplier-contract-relationship.pspc
      issuer_url: $APPLICATION_URL/pspc/pspc-supplier-contract-relationship-credential
      credential:
        effective_date:
          input: effective_date
          from: claim
      topic:
        related_source_id:
          input: contract_subject_id
          from: claim
        related_type:
          input: pspc-contract-supplier-relationship.pspc
          from: value
        source_id:
          input: supplier_subject_id
          from: claim
        type:
          input: pspc-supplier-contract-relationship.pspc
          from: value
      cardinality_fields:
        - contract_subject_id
      mapping:
      - model: attribute
        fields:
          type:
            input: supplier_subject_id
            from: value
          value:
            input: supplier_subject_id
            from: claim
      - model: attribute
        fields:
          type:
            input: contract_subject_id
            from: value
          value:
            input: contract_subject_id
            from: claim
      - model: attribute
        fields:
          type:
            input: effective_date
            from: value
          format:
            input: datetime
            from: value
          value:
            input: effective_date
            from: claim

    - description: The relationship between Suppliers and Contracts
      schema: pspc-contract-supplier-relationship.pspc
      issuer_url: $APPLICATION_URL/pspc/pspc-contract-supplier-relationship-credential
      credential:
        effective_date:
          input: effective_date
          from: claim
      topic:
        source_id:
          input: contract_subject_id
          from: claim
        type:
          input: pspc-contract-supplier-relationship.pspc
          from: value
        related_source_id:
          input: supplier_subject_id
          from: claim
        related_type:
          input: pspc-supplier-contract-relationship.pspc
          from: value
      cardinality_fields:
        - supplier_subject_id
      mapping:
      - model: attribute
        fields:
          type:
            input: supplier_subject_id
            from: value
          value:
            input: supplier_subject_id
            from: claim
      - model: attribute
        fields:
          type:
            input: contract_subject_id
            from: value
          value:
            input: contract_subject_id
            from: claim
      - model: attribute
        fields:
          type:
            input: effective_date
            from: value
          format:
            input: datetime
            from: value
          value:
            input: effective_date
            from: claim

verifiers:
  bctob:
    name: PSPC OrgBook
    alias: vcr-agent
    connection:
      type: TheOrgBook
      api_url: $TOB_API_URL
      agent_admin_url: $TOB_AGENT_ADMIN_URL              
### eof ###
