default:
  APPLICATION_URL_GC: $APPLICATION_URL/gc/gc-creds
  TEMPLATE_PATH: ../templates

  TOB_API_URL: http://tob-api:8080/api/v2
  TOB_APP_URL: http://localhost:8085

  WALLET_SEED_PSPC: pspc_000000000000000000000000000

  #INDY_GENESIS_URL: http://localhost:9000/genesis

  #LEDGER_PROTOCOL_VERSION: "1.6"
  #AUTO_REGISTER_DID: true

### eof ###
